In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [63]:
data = np.load("./data/createdata.npy")
data.shape

(10000, 11)

In [64]:
np.max(data,axis=0)

array([1.02523178e+02, 5.82615889e+02, 1.05106720e+05, 1.00000000e+00,
       9.18640124e+00, 3.40010257e+05, 6.96438897e+00, 2.38006880e+06,
       1.39000000e+02, 3.40106257e+05, 1.00000000e+00])

In [65]:
minmax = lambda data:(data - np.min(data,axis=0))/(np.max(data,axis=0) - np.min(data,axis=0))

data[:,:-1] = minmax(data[:,:-1])

In [66]:
np.random.seed(1234)
train,test = train_test_split(data,train_size=0.7)

In [67]:
train.shape

(7000, 11)

In [68]:
np.save("./data/train",train)
np.save("./data/test",test)

In [1]:
train[-4]

NameError: name 'train' is not defined

In [ ]:
train = np.load("./data/train.npy")
train

In [4]:
train = np.load("./data/train.npy")
train

array([[0.58712047, 0.58712047, 0.31392063, ..., 0.2739726 , 0.3737155 ,
        1.        ],
       [0.38311692, 0.38311692, 0.11766535, ..., 0.38356164, 0.17506987,
        1.        ],
       [0.45471088, 0.45471088, 0.1757881 , ..., 0.64383562, 0.23650439,
        1.        ],
       ...,
       [0.73564044, 0.73564044, 0.51618323, ..., 0.38356164, 0.56445709,
        1.        ],
       [0.44899708, 0.44899708, 0.17072246, ..., 0.60273973, 0.2312657 ,
        1.        ],
       [0.53869814, 0.53869814, 0.25879274, ..., 0.73972603, 0.32002907,
        0.        ]])

In [5]:
train.shape

(7000, 11)

In [43]:
data[:20]

array([[ 1.00000000e+00,  7.50000000e+01,  2.20231658e+04,
         4.99099514e+01,  6.22881869e+00,  5.68431749e+03,
         6.95820812e+00,  3.97872224e+04,  9.40000000e+01,
         5.77831749e+03,  1.00000000e+00],
       [ 1.00000000e+00,  7.50000000e+01,  2.20231658e+04,
         4.22308857e+01,  6.22881869e+00,  5.68431749e+03,
         6.95820812e+00,  3.97872224e+04,  9.70000000e+01,
         5.78131749e+03,  1.00000000e+00],
       [ 1.00000000e+00,  7.50000000e+01,  2.20231658e+04,
         4.13692850e+01,  6.22881869e+00,  5.68431749e+03,
         6.95820812e+00,  3.97872224e+04,  8.80000000e+01,
         5.77231749e+03,  1.00000000e+00],
       [ 1.00000000e+00,  7.50000000e+01,  2.20231658e+04,
         2.49802571e+01,  6.22881869e+00,  5.68431749e+03,
         6.95820812e+00,  3.97872224e+04,  9.30000000e+01,
         5.77731749e+03,  1.00000000e+00],
       [ 1.00000000e+00,  7.50000000e+01,  2.20231658e+04,
         1.92007374e+01,  6.22881869e+00,  5.68431749e+03,
  

In [61]:
data[:,-3]

array([105., 103.,  95., ...,  98.,  95.,  93.])

In [2]:
!which python

/home/amax/.conda/envs/pytorch/bin/python
